<!doctype html>
<html lang="pt-BR">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Inteligência Gov | AssessorGov IA</title>
<style>:root{--bg:#07111f;--panel:#0d1b2d;--line:#243b58;--text:#f4f7fb;--muted:#aebed0;--accent:#7dd3fc;--ok:#36d399;--warn:#f6c453;--risk:#fb7185}*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,Arial;background:var(--bg);color:var(--text)}.shell{display:grid;grid-template-columns:240px 1fr;min-height:100vh}.side{padding:24px 18px;border-right:1px solid var(--line)}.brand{font-weight:900}.product{color:var(--accent);font-size:13px;margin:6px 0 28px}.nav a{display:block;color:var(--muted);text-decoration:none;padding:11px 12px;border-radius:10px;margin:4px 0}.nav a.active{background:#10243a;color:white}main{padding:28px;max-width:1500px}.top{display:flex;justify-content:space-between;gap:20px;align-items:start}.top h1{margin:0 0 6px}.muted{color:var(--muted)}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:24px 0}.card{background:var(--panel);border:1px solid var(--line);border-radius:16px;padding:18px}.stat strong{display:block;font-size:26px;margin-top:7px}.grid{display:grid;grid-template-columns:2fr 1fr;gap:18px}.item{padding:18px 0;border-top:1px solid var(--line)}.item:first-child{border-top:0}.tag{display:inline-block;padding:5px 9px;border-radius:99px;font-size:12px;font-weight:800;border:1px solid var(--line)}.high{color:var(--warn)}.critical{color:var(--risk)}.confirmed{color:var(--ok)}h2{font-size:18px}.item h3{margin:10px 0 7px;font-size:17px}.item p{color:var(--muted);line-height:1.55}.actions{display:flex;gap:9px;flex-wrap:wrap}.btn{display:inline-block;text-decoration:none;color:#032016;background:var(--ok);padding:9px 12px;border-radius:9px;font-weight:800;font-size:13px}.btn.secondary{color:var(--text);background:#142a40;border:1px solid var(--line)}.deadline{padding:12px 0;border-top:1px solid var(--line)}@media(max-width:900px){.shell{grid-template-columns:1fr}.side{display:none}.stats{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}}@media(max-width:520px){.stats{grid-template-columns:1fr}.top{display:block}}</style></head>
<body><div class="shell"><aside class="side"><div class="brand">VITRINE IA PRO</div><div class="product">AssessorGov IA</div><nav class="nav"><a href="/">Visão geral</a><a href="#radar">Radar de oportunidades</a><a class="active" href="{{ route('gov.intelligence') }}">Inteligência Gov</a><a href="{{ route('gov.compliance') }}">Compliance e habilitação</a><a href="#documentos">Documentos</a></nav></aside><main>
<div class="top"><div><h1>Inteligência Gov</h1><div class="muted">@if($customer) Impactos regulatórios para {{ $customer->trade_name ?: $customer->legal_name }}. @else Mudanças oficiais traduzidas em impacto, risco e ação para seu perfil. @endif</div></div><span class="tag confirmed">Atualização semanal</span></div>
<section class="stats"><div class="card stat"><span class="muted">Novas mudanças</span><strong>{{ $stats['new_changes'] }}</strong></div><div class="card stat"><span class="muted">Exigem ação</span><strong>{{ $stats['requires_action'] }}</strong></div><div class="card stat"><span class="muted">Oportunidades</span><strong>{{ $stats['opportunities'] }}</strong></div><div class="card stat"><span class="muted">Em monitoramento</span><strong>{{ $stats['monitoring'] }}</strong></div></section>
<div class="grid"><section class="card"><h2>Impactos para sua empresa</h2>
@foreach($items as $item)
<article class="item">
<span class="tag {{ $item['priority'] === 'critical' ? 'critical' : ($item['priority'] === 'high' ? 'high' : '') }}">{{ strtoupper($item['priority']) }} · {{ strtoupper(str_replace('_',' ',$item['impact_class'])) }}</span>
<h3>{{ $item['title'] }}</h3>
<p><strong>Fato confirmado:</strong> {{ $item['fact'] }}</p>
<p><strong>Análise:</strong> {{ $item['analysis'] }}</p>
<p><strong>Impacto para você:</strong> {{ $item['personalized_reason'] }}</p>
<p><strong>Ação recomendada:</strong> {{ $item['action'] }}</p>
<div class="actions">@if($item['relevant'])<form method="POST" action="{{ route('gov.intelligence.apply', $item['id']) }}" style="display:inline">@csrf<button class="btn" type="submit" style="border:0;cursor:pointer">Aplicar ao meu cadastro</button></form>@endif<a class="btn secondary" href="{{ $item['source_url'] }}" target="_blank" rel="noopener">Fonte oficial · {{ $item['source_label'] }}</a></div>
</article>
@endforeach
</section><aside><section class="card"><h2>Prioridades da semana</h2>@forelse($priorities as $priority)<div class="deadline"><strong>{{ $loop->iteration }}. {{ $priority['title'] }}</strong><div class="muted">{{ $priority['action'] }}</div></div>@empty<div class="muted">Nenhuma ação crítica identificada.</div>@endforelse</section><section class="card" style="margin-top:18px"><h2>Como o sistema classifica</h2><p class="muted">Fato confirmado é separado de análise. A relevância considera o cadastro da empresa, os canais das oportunidades vinculadas e a etapa atual da jornada.</p><span class="tag critical">Crítico</span> <span class="tag high">Alto</span> <span class="tag">Médio</span> <span class="tag confirmed">Informativo</span></section></aside></div>
</main></div></body></html>