<!doctype html>
<html lang="pt-BR">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $opportunity->title }} | AssessorGov Cultura</title>
<style>
:root{--bg:#07111f;--panel:#0d1b2d;--line:#203550;--text:#edf5ff;--muted:#9fb2c9;--accent:#7c5cff;--green:#31c48d;--warn:#f7b955}*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,Arial;background:#07111f;color:var(--text)}.shell{max-width:1050px;margin:auto;padding:28px 18px 60px}.top{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:22px}.brand{font-weight:800;font-size:20px}.brand span{color:#a996ff}a{color:#b8c7ff}.card{background:var(--panel);border:1px solid var(--line);border-radius:18px;padding:22px;margin-bottom:16px}.tag{display:inline-block;padding:6px 10px;border-radius:999px;background:#14283f;color:#c9d8ea;font-size:12px;margin:3px}.score{font-size:34px;font-weight:900;color:var(--green)}.grid{display:grid;grid-template-columns:2fr 1fr;gap:16px}.muted{color:var(--muted)}.facts{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.fact{background:#091523;border:1px solid #1e344e;border-radius:12px;padding:13px}.btn{display:inline-block;border-radius:11px;padding:12px 16px;font-weight:800;text-decoration:none}.primary{background:var(--accent);color:#fff}.secondary{background:#15283e;color:#e2ecf7}.locked{border:1px solid #6d5530;background:#251f16}.list{padding-left:20px;line-height:1.7}@media(max-width:760px){.grid,.facts{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}}
</style></head>
<body><div class="shell">
<div class="top"><div class="brand">AssessorGov <span>Cultura</span></div><a href="{{ route('cultura.dashboard') }}">← Voltar ao Radar</a></div>
<div class="grid"><main>
<div class="card"><div class="muted">{{ $opportunity->source_name ?? $opportunity->agency ?? 'Fonte oficial' }}</div><h1>{{ $opportunity->title }}</h1>@if($opportunity->cultural_areas)@foreach($opportunity->cultural_areas as $area)<span class="tag">{{ $area }}</span>@endforeach @endif<p>{{ $opportunity->summary }}</p></div>
<div class="card"><h2>Informações da oportunidade</h2><div class="facts"><div class="fact"><small class="muted">Prazo</small><br><strong>{{ $opportunity->closes_at?->format('d/m/Y') ?? 'Consulte o edital' }}</strong></div><div class="fact"><small class="muted">Abrangência</small><br><strong>{{ $opportunity->municipality ?: 'Estado de São Paulo' }}</strong></div><div class="fact"><small class="muted">Valor mínimo</small><br><strong>{{ $opportunity->budget_min ? 'R$ '.number_format($opportunity->budget_min,2,',','.') : 'Conforme edital' }}</strong></div><div class="fact"><small class="muted">Valor máximo</small><br><strong>{{ $opportunity->budget_max ? 'R$ '.number_format($opportunity->budget_max,2,',','.') : 'Conforme edital' }}</strong></div></div></div>
@if($opportunity->eligibility_rules)<div class="card"><h2>Elegibilidade</h2><ul class="list">@foreach($opportunity->eligibility_rules as $rule)<li>{{ is_string($rule) ? $rule : json_encode($rule, JSON_UNESCAPED_UNICODE) }}</li>@endforeach</ul></div>@endif
<div class="card"><h2>Fonte oficial</h2><p class="muted">Confira sempre o edital e seus anexos na fonte oficial antes de enviar sua inscrição.</p><a class="btn secondary" target="_blank" rel="noopener" href="{{ $opportunity->official_url }}">Abrir fonte oficial ↗</a></div>
</main><aside>
<div class="card"><div class="muted">Aderência ao seu perfil</div>@if($match)<div class="score">{{ $match['score'] }}%</div>@if(!empty($match['reasons']))<ul class="list">@foreach($match['reasons'] as $reason)<li>{{ $reason }}</li>@endforeach</ul>@endif @else<p>Complete seu Perfil Cultural para calcular a aderência.</p><a class="btn secondary" href="{{ route('cultura.profile.edit') }}">Completar perfil</a>@endif</div>
<div class="card {{ $canUseAi ? '' : 'locked' }}"><h3>IA Cultural</h3>@if($canUseAi)<p class="muted">Seu plano permite análise assistida do edital e apoio à elaboração.</p><span class="btn primary">Analisar com IA</span>@else<p>🔒 A análise do edital e a elaboração assistida estão disponíveis nos planos pagos.</p><a class="btn primary" href="#">Conhecer planos</a>@endif</div>
<div class="card"><small class="muted">Seu plano</small><h3 style="text-transform:capitalize">{{ $planSlug }}</h3><div class="muted">Radar: {{ $limits['radar_limit'] ?? 'Personalizado' }} oportunidades</div><div class="muted">Monitoramentos: {{ $limits['active_monitoring_limit'] ?? 'Personalizado' }}</div></div>
</aside></div></div></body></html>
